/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GuessuImport } from './routes/guessu'
import { Route as GalsImport } from './routes/gals'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const GuessuRoute = GuessuImport.update({
  path: '/guessu',
  getParentRoute: () => rootRoute,
} as any)

const GalsRoute = GalsImport.update({
  path: '/gals',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/gals': {
      preLoaderRoute: typeof GalsImport
      parentRoute: typeof rootRoute
    }
    '/guessu': {
      preLoaderRoute: typeof GuessuImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  GalsRoute,
  GuessuRoute,
])

/* prettier-ignore-end */
